## One-d-array

In [18]:
one_d_array = np.array([0.3, 0.2, 0.5])
one_d_array

array([0.3, 0.2, 0.5])

## Scaling One-d-array

In [54]:
z = 2
scaled_array = z * one_d_array
scaled_array

array([0.6, 0.4, 1. ])

In [42]:
one_d_array.shape

(3,)

## Two-d-array

In [52]:
two_d_array = np.array([[ 0,  1,  2],
       [10, 11, 12]])
two_d_array

array([[ 0,  1,  2],
       [10, 11, 12]])

In [48]:
two_d_array.shape

(2, 3)

## Three-d-array

In [53]:
three_d_array = np.array([
    [[1, 2, 3], 
     [3, 4, 5]], 
    [[5, 6, 7], 
     [7, 8, 9.5]]])
three_d_array

array([[[1. , 2. , 3. ],
        [3. , 4. , 5. ]],

       [[5. , 6. , 7. ],
        [7. , 8. , 9.5]]])

In [50]:
three_d_array.shape

(2, 2, 3)

# L1 Norm

In [19]:
from numpy import array
from numpy.linalg import norm
norm_l1 = norm(one_d_array, 1)
print(norm_l1)

1.0


## L2 Norm

In [58]:
from numpy import array
from numpy.linalg import norm
arr = array([5,12])
norm_l2 = norm(arr)
print(norm_l2)

13.0


##  Vector Multipication

In [21]:
import numpy
first =np.array([3,4,5])
second = np.array([4,5,6])
v_multipication = first * second
print(v_multipication)

[12 20 30]


## Vector Dot Operation

In [23]:
import numpy
first =np.array([3,4,5])
second = np.array([4,5,6])
v_multipication = first.dot(second)
print(v_multipication)

62


## Matrix-Matrix Multipication

In [4]:
from numpy import array
first = array([[2,3],[4,5],[6,7]])
second = array([[5,6],[7,8]])
mm_multipication = first.dot(second)
print(mm_multipication)

[[31 36]
 [55 64]
 [79 92]]


array([[2, 3],
       [4, 5],
       [6, 7]])

In [5]:
second

array([[5, 6],
       [7, 8]])

## Matrix-Vector Multipication

In [2]:
from numpy import array
first = array([[2,3],[4,5]])
second= array([3, 4])
mv_multipication = first.dot(second)
print(mv_multipication)

[18 32]


## Matrix-Scalar Multipication

In [6]:
from numpy import array
first = array([[2,3],[4,5]])
scalar= 3
ms_multipication = first * scalar 
print(ms_multipication)

[[ 6  9]
 [12 15]]


## Transpose

In [9]:
from numpy import array
first = array([[2,3],[4,5],[6,7]])
print(first)
transpose = first.T
print(transpose)

[[2 3]
 [4 5]
 [6 7]]
[[2 4 6]
 [3 5 7]]


## Inverse

In [12]:
from numpy import array
import numpy as np
first = array([[2,3],[4,5]])
second = np.linalg.inv(first)
print(second)

[[-2.5  1.5]
 [ 2.  -1. ]]


## Determinant

In [14]:
from numpy import array
import numpy as np
first = array([[2,3],[4,5]])
second = np.linalg.det(first)
print(second)

-2.0


# Special Matrixes

## Square Matrix

In [52]:
first = array([[2,3,8],[4,5,9],[6,7,1]])
shape = first.shape
row = first.shape[0]
column = first.shape[1]
print('Matrix shape is: {} \nNumber of row:{} \nNumber of column:{}'.format(shape,column,row))

Matrix shape is: (3, 3) 
Number of row:3 
Number of column:3


## Identity Matrix

In [53]:
from numpy import identity
Identity = identity(5)
print(Identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Diagonal Matrix

In [58]:
import numpy as np
first = np. array([[2,0,0],[0,5,0],[0,0,1]])
first

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 1]])

# Reshaping Dimension

## 1D to 2D

In [84]:
import numpy as np
one_d_array = np.array([0.3, 0.2, 0.5])
print(one_d_array.shape)
reshaped = one_d_array.reshape(one_d_array.shape[0], 1)
print(reshaped.shape)

(3,)
(3, 1)


## 2D to 3D

In [7]:
import numpy as np
first = np.array([[2,0,0],[0,5,0],[0,0,1]])
print(first.shape)
reshaped = first.reshape(first.shape[0], first.shape[1],1)
print(reshaped.shape)

(3, 3)
(3, 3, 1)
